---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Create the ELB only listening over port 80
      ec2_elb_lb:
        name: ComcastELB
        state: present
        region: us-east-1
        zones:
              - us-east-1a
              - us-east-1b
        listeners:
              - protocol: http
                load_balancer_port: 80
                instance_port: 80
      register: elb    

